name: Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test with Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          path: src/github.com/sunshineplan/gohttp

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.x'

      - name: Setup GOPATH
        run: |
          echo "GOPATH=${{ github.workspace }}" >> "$GITHUB_ENV"
          echo "${{ github.workspace }}/bin" >> "$GITHUB_PATH"

      - name: Run Unit tests
        run: go test -race -covermode atomic -coverprofile=covprofile ./...
        working-directory: src/github.com/sunshineplan/gohttp

      - name: Install goveralls
        run: go install github.com/mattn/goveralls@latest

      - name: Send coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: goveralls -coverprofile=covprofile -service=github
        working-directory: src/github.com/sunshineplan/gohttp
